### ISSUE TITLE
Text shifted a little bit too high

### ISSUE THREAD

**Issue by NikTheDusky** [zagortenay333/Harmattan#19] opened 2016-06-18 17:36 UTC
I don't know if it's the same problem as in #1, but all my text is shifted a few pixels above of the normal place.
![A screenshot showing the problem.](https://cloud.githubusercontent.com/assets/2510608/16172952/a9563132-3593-11e6-8e36-9216ba8990d6.png)

Currently using Ubuntu 16.04 LTS with the standard Unity Desktop and conky 1.10.1 with the Numix theme and normal God-Mode. This is happening in all other themes with or without photo mode too.

Otherwise, this theme is awesome, keep up the good work! :D

**Comment by zagortenay333** [comment] 2016-06-18 18:03
Duplicate of #1

**Closed as completed by zagortenay333** 2016-06-18 18:03 UTC
