### ISSUE TITLE
Weird background and aligment

### ISSUE THREAD

**Issue by farika** [zagortenay333/Harmattan#33] opened 2017-05-03 20:58 UTC
Hello,

I try to use your theme on my fedora. Conky, curl, jq, and droidless are installed.
.harmattan-assets is in the root of my user folder, as well as the conkyrc that matches the theme. I tried several themes in god mode.

The alignment of the text is incorrect and conky copies a part from elsewhere on my screen that corresponds to the terminal.
![capture d ecran de 2017-05-03 16-36-47](https://cloud.githubusercontent.com/assets/12280780/25681340/3793bcba-3054-11e7-9257-6786450594f6.jpg)

Thanks for your help

**Comment by zagortenay333** [comment] 2017-05-04 13:22
Duplicate of #1 and #3.

**Closed as completed by zagortenay333** 2017-05-04 13:22 UTC
