### ISSUE TITLE
Transparent theme on Debian Stretch

### ISSUE THREAD

**Issue by zoof** [zagortenay333/Harmattan#43] opened 2017-08-02 18:13 UTC
After upgrading to Debian Stretch (conky version 1.10.6), the Transparent theme is no longer transparent imgur.com/a/Rg8u8. Current master of Harmattan.

**Comment by zagortenay333** [comment] 2017-08-02 18:17
Duplicate of #3

**Closed as completed by zagortenay333** 2017-08-02 18:17 UTC
