### ISSUE TITLE
Border arround.

### ISSUE THREAD

**Issue by Peloponeso31** [zagortenay333/Harmattan#46] opened 2017-09-19 03:19 UTC
It's not the black border, is a transparent one, i don't know what to do to get rid of it.
![image](https://user-images.githubusercontent.com/32084752/30574422-67241916-9cbf-11e7-805f-a0fa8cadd9f3.png)

**Comment by Peloponeso31** [comment] 2017-09-19 03:25
i just realize how to fix it, anyway if someone is having the same problem than me, you just change: "own_window_type = "override" " without the quotes. sorry for the inconveniece.

![image](https://user-images.githubusercontent.com/32084752/30574544-43c88a64-9cc0-11e7-97d6-b5e4c1bf1b5b.png)

**Comment by zagortenay333** [comment] 2017-09-19 08:42
Duplicate of #13

**Closed as completed by zagortenay333** 2017-09-19 08:42 UTC
