### ISSUE TITLE
Conky 1.10 - Assuming it's in old syntax and attempting

### ISSUE THREAD

**Issue by nicolasdanelon** [zagortenay333/Harmattan#6] opened 2015-07-01 04:33 UTC
Hi, great job, and thanks for using github!

Well.. I'm an ArchLinux user and with the last update.. 

```
$ conky -v
conky 1.10.0 compiled Tue Jun 30 06:56:49 TAHT 2015 for Linux 4.0.6-1-ARCH x86_64
```

I get this erros:

```
conky: Syntax error (/home/nicolasm/.conkyrc:2: syntax error near 'yes') while reading config file. 
conky: Assuming it's in old syntax and attempting conversion.
conky: Invalid value 'undecorate' for setting 'own_window_hints'. Valid values are: 'undecorated', 'below', 'above', 'sticky', 'skip_taskbar', 'skip_pager'.
conky: desktop window (a00016) is subwindow of root window (c0)
conky: window type - normal
conky: drawing to created window (0xc00002)
conky: drawing to double buffer
conky: forked to background, pid is 1498
```

conky does not work correctly. See screenshot:
![Imgur](http://i.imgur.com/BaDE3IT.png)

And if I try to follow this instructions :
https://bbs.archlinux.org/viewtopic.php?pid=1540862#p1540862

y get this:
![Imgur](http://i.imgur.com/QUySn55.png)

I try to do something like this `/usr/share/doc/conky-1.10.0/conky.conf` 

```
conky.config = {
    alignment = 'top_left',
    background = false,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'white',
    default_outline_color = 'white',
    default_shade_color = 'white',
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    use_xft = true,
    font = 'DejaVu Sans Mono:size=12',
    gap_x = 5,
    gap_y = 60,
    minimum_height = 5,
    minimum_width = 5,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_stderr = false,
    extra_newline = false,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    show_graph_scale = false,
    show_graph_range = false
}

conky.text = [[
${scroll 16 $nodename - $sysname $kernel on $machine | }
$hr
${color grey}Uptime:$color $uptime
${color grey}Frequency (in MHz):$color $freq
${color grey}Frequency (in GHz):$color $freq_g
${color grey}RAM Usage:$color $mem/$memmax - $memperc% ${membar 4}
${color grey}Swap Usage:$color $swap/$swapmax - $swapperc% ${swapbar 4}
${color grey}CPU Usage:$color $cpu% ${cpubar 4}
${color grey}Processes:$color $processes  ${color grey}Running:$color $running_processes
$hr
${color grey}File systems:
 / $color${fs_used /}/${fs_size /} ${fs_bar 6 /}
${color grey}Networking:
Up:$color ${upspeed eth0} ${color grey} - Down:$color ${downspeed eth0}
$hr
${color grey}Name              PID   CPU%   MEM%
${color lightgrey} ${top name 1} ${top pid 1} ${top cpu 1} ${top mem 1}
${color lightgrey} ${top name 2} ${top pid 2} ${top cpu 2} ${top mem 2}
${color lightgrey} ${top name 3} ${top pid 3} ${top cpu 3} ${top mem 3}
${color lightgrey} ${top name 4} ${top pid 4} ${top cpu 4} ${top mem 4}
]]
```

I get tihs but doesn't work

```
conky.config = {
    background = true,
    update_interval = 1,
    double_buffer = true,
    no_buffers = true,
    imlib_cache_size = 10,
    gap_x = 1050,
    gap_y = 90,
    minimum_size = '268 620',
    maximum_width = 268,
    own_window = true,
    own_window_type = 'normal',
    own_window_transparent = true,
    own_window_hints = 'undecorate,sticky,skip_taskbar,skip_pager,below',
    border_inner_margin = 0,
    border_outer_margin = 0,
    own_window_argb_visual = true,
    draw_shades = false,
    default_shade_color = 'AAAAAA',
    draw_outline = false,
    default_outline_color = 'AAAAAA',
    draw_borders = false,
    draw_graph_borders = false,
    default_graph_size = '26 80',
    show_graph_scale = false,
    show_graph_range = false,
    use_xft = true,
    xftalpha = 0,
    xftfont = 'Droid Sans:size=8',
    text_buffer_size = 256,
    override_utf8_locale = true,
    short_units = true,
    pad_percents = 2,
    top_name_width = 7,
    default_color = 'DCDCDC',
    color1 = 'DCDCDC',
    color2 = 'DCDCDC',
    color3 = 'DCDCDC',
    color4 = 'F9F9F9',
    color5 = 'D64937',
    color6 = '888888',
    color7 = '484848',
    color8 = '2D2D2D'
}
conky.text = [[
    ${execi 300 curl -s "http://weather.yahooapis.com/forecastrss?w=44418&u=c" -o ~/.cache/weather.xml}
    ${image ~/.harmattan-assets/misc/Numix/God-Mode/top-bg.png -p 20,30 -s 228x61}
    ${image ~/.harmattan-assets/misc/Numix/God-Mode/bottom-bg.png -p 20,473 -s 228x119}
    ${execi 300 cp -f ~/.harmattan-assets/photos/smallest/$(grep "yweather:condition" ~/.cache/weather.xml | grep -o "code=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*").png ~/.cache/weather.png}${image ~/.cache/weather.png -p 20,91 -s 228x86}
    ${image ~/.harmattan-assets/misc/Numix/God-Mode/border.png -p 20,91 -s 228x86}
    ${image ~/.harmattan-assets/misc/Numix/God-Mode/bg-1.png -p 20,177 -s 228x86}
    ${image ~/.harmattan-assets/misc/Numix/God-Mode/bg-2.png -p 20,263 -s 228x105}
    ${image ~/.harmattan-assets/misc/Numix/God-Mode/bg-3.png -p 20,368 -s 228x105}
    ${image ~/.harmattan-assets/misc/Numix/God-Mode/bg-4.png -p 20,478 -s 228x14}
    ${image ~/.harmattan-assets/misc/Numix/God-Mode/separator-v.png -p 95,185 -s 1x76}
    ${image ~/.harmattan-assets/misc/Numix/God-Mode/separator-v.png -p 172,185 -s 1x76}
    ${image ~/.harmattan-assets/misc/Numix/God-Mode/separator-h.png -p 33,369 -s 202x1}
    ${image ~/.harmattan-assets/misc/Numix/God-Mode/separator-h.png -p 33,269 -s 202x1}

    ${color3}${voffset 172}${alignc 77}${execi 300 grep "yweather:forecast" ~/.cache/weather.xml | grep -o "day=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*" | awk 'NR==1' | tr '[a-z]' '[A-Z]'}${color}
    ${color3}${voffset -13}${alignc}${execi 300 grep "yweather:forecast" ~/.cache/weather.xml | grep -o "day=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*" | awk 'NR==2' | tr '[a-z]' '[A-Z]'}${color}
    ${color3}${voffset -13}${alignc -77}${execi 300 grep "yweather:forecast" ~/.cache/weather.xml | grep -o "day=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*" | awk 'NR==3' | tr '[a-z]' '[A-Z]'}${color}

    ${color2}${voffset 51}${alignc 77}${execi 300 grep "yweather:forecast" ~/.cache/weather.xml | grep -o "low=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*" | awk 'NR==1'}°/${execi 300 grep "yweather:forecast" ~/.cache/weather.xml | grep -o "high=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*" | awk 'NR==1'}°${color}
    ${color2}${voffset -13}${alignc}${execi 300 grep "yweather:forecast" ~/.cache/weather.xml | grep -o "low=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*" | awk 'NR==2'}°/${execi 300 grep "yweather:forecast" ~/.cache/weather.xml | grep -o "high=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*" | awk 'NR==2'}°${color}
    ${color2}${voffset -13}${alignc -77}${execi 300 grep "yweather:forecast" ~/.cache/weather.xml | grep -o "low=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*" | awk 'NR==3'}°/${execi 300 grep "yweather:forecast" ~/.cache/weather.xml | grep -o "high=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*" | awk 'NR==3'}°${color}

    ${goto 36}${voffset -172}${font Droid Sans :size=36}${color4}${execi 300 grep "yweather:condition" ~/.cache/weather.xml | grep -o "temp=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*"}°${font}${color}
    ${goto 46}${voffset 14}${font Droid Sans :size=12}${color4}${execi 300 grep "yweather:condition" ~/.cache/weather.xml | grep -o "text=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*"}${font}${color}
    ${color4}${alignr 52}${voffset -73}${execi 300 grep "yweather:atmosphere" ~/.cache/weather.xml | grep -o "pressure=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*"} ${execi 300 grep "yweather:units" ~/.cache/weather.xml | grep -o "pressure=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*"}
    ${color4}${alignr 52}${voffset 7}${execi 300 grep "yweather:atmosphere" ~/.cache/weather.xml | grep -o "humidity=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*"} %${color}
    ${color4}${alignr 52}${voffset 7}${execi 300 grep "yweather:wind" ~/.cache/weather.xml | grep -o "speed=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*"} ${execi 300 grep "yweather:units" ~/.cache/weather.xml | grep -o "speed=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*"}${color}

    ${voffset -117}${font Droid Sans Mono :size=22}${alignc}${color2}${time %H:%M}${font}${color}
    ${voffset 4}${font Droid Sans :size=10}${alignc}${color6}${time %A, %B %d}${font}${color}

    ${voffset 294}${goto 40}${color5}Cpu:${color}
    ${voffset 4}${goto 40}${color5}Mem:${color}
    ${voffset 4}${goto 40}${color5}Uptime:${color}
    ${voffset -47}${alignr 39}${color6}${cpu cpu0}%${color}
    ${voffset 4}${alignr 39}${color6}${memperc}%${color}
    ${voffset 4}${alignr 39}${color6}${uptime_short}${color}
    ${voffset -47}${alignc}${color2}${cpubar 5,36}${color}
    ${voffset 4}${alignc}${color2}${membar 5,36}${color}
    ${voffset 29}${goto 40}${loadgraph 26,190 D64937 D64937 -l}

    ${voffset 26}${goto 40}${color5}${top_mem name 1}${color}
    ${voffset 4}${goto 40}${color5}${top_mem name 2}${color}
    ${voffset 4}${goto 40}${color5}${top_mem name 3}${color}
    ${voffset 4}${goto 40}${color5}${top_mem name 4}${color}
    ${voffset 4}${goto 40}${color5}${top_mem name 5}${color}
    ${voffset -81}${alignc}${color2}${top_mem mem 1}%${color}
    ${voffset 4}${alignc}${color2}${top_mem mem 2}%${color}
    ${voffset 4}${alignc}${color2}${top_mem mem 3}%${color}
    ${voffset 4}${alignc}${color2}${top_mem mem 4}%${color}
    ${voffset 4}${alignc}${color2}${top_mem mem 5}%${color}
    ${voffset -81}${alignr 39}${color6}${top_mem mem_res 1}${color}
    ${voffset 4}${alignr 39}${color6}${top_mem mem_res 2}${color}
    ${voffset 4}${alignr 39}${color6}${top_mem mem_res 3}${color}
    ${voffset 4}${alignr 39}${color6}${top_mem mem_res 4}${color}
    ${voffset 4}${alignr 39}${color6}${top_mem mem_res 5}${color}
    ${voffset -104}${goto 40}${color1}Proc${color}
    ${voffset -13}${alignc}${color1}Mem%${color}
    ${voffset -13}${alignr 39}${color1}Mem${color}

    ${if_existing /proc/net/route ppp0}
    ${voffset -227}${goto 40}${color5}Up: ${color2}${upspeed ppp0}${color5}${goto 150}Down: ${color2}${downspeed ppp0}
    ${voffset 10}${goto 40}${upspeedgraph ppp0 26,80 d64937 d64937}${goto 150}${downspeedgraph ppp0 26,80 d64937 d64937}
    ${voffset 9}${goto 40}${color5}Sent: ${color2}${totalup ppp0}${color5}${goto 150}Received: ${color2}${totaldown ppp0}
    ${else}
    ${if_existing /proc/net/route ppp1}
    ${voffset -240}${goto 40}${color5}Up: ${color2}${upspeed ppp1}${color5}${goto 150}Down: ${color2}${downspeed ppp1}
    ${voffset 10}${goto 40}${upspeedgraph ppp1 26,80 d64937 d64937}${goto 150}${downspeedgraph ppp1 26,80 d64937 d64937}
    ${voffset 9}${goto 40}${color5}Sent: ${color2}${totalup ppp1}${color5}${goto 150}Received: ${color2}${totaldown ppp1}
    ${else}
    ${if_existing /proc/net/route wlp2s1}
    ${voffset -253}${goto 40}${color5}Up: ${color2}${upspeed wlp2s1}${color5}${goto 150}Down: ${color2}${downspeed wlp2s1}
    ${voffset 10}${goto 40}${upspeedgraph wlp2s1 26,80 d64937 d64937}${goto 150}${downspeedgraph wlp2s1 26,80 d64937 d64937}
    ${voffset 9}${goto 40}${color5}Sent: ${color2}${totalup wlp2s1}${color5}${goto 150}Received: ${color2}${totaldown wlp2s1}
    ${else}
    ${if_existing /proc/net/route wlp2s0}
    ${voffset -266}${goto 40}${color5}Up: ${color2}${upspeed wlp2s0}${color5}${goto 150}Down: ${color2}${downspeed wlp2s0}
    ${voffset 10}${goto 40}${upspeedgraph wlp2s0 26,80 d64937 d64937}${goto 150}${downspeedgraph wlp2s0 26,80 d64937 d64937}
    ${voffset 9}${goto 40}${color5}Sent: ${color2}${totalup wlp2s0}${color5}${goto 150}Received: ${color2}${totaldown wlp2s0}
    ${else}
    ${if_existing /proc/net/route wlan0}
    ${voffset -279}${goto 40}${color5}Up: ${color2}${upspeed wlan0}${color5}${goto 150}Down: ${color2}${downspeed wlan0}
    ${voffset 8}${goto 40}${upspeedgraph wlan0 26,80 d64937 d64937}${goto 150}${downspeedgraph wlan0 26,80 d64937 d64937}
    ${voffset 9}${goto 40}${color5}Sent: ${color2}${totalup wlan0}${color5}${goto 150}Received: ${color2}${totaldown wlan0}
    ${else}
    ${if_existing /proc/net/route wlan1}
    ${voffset -292}${goto 40}${color5}Up: ${color2}${upspeed wlan1}${color5}${goto 150}Down: ${color2}${downspeed wlan1}
    ${voffset 10}${goto 40}${upspeedgraph wlan1 26,80 d64937 d64937}${goto 150}${downspeedgraph wlan1 26,80 d64937 d64937}
    ${voffset 9}${goto 40}${color5}Sent: ${color2}${totalup wlan1}${color5}${goto 150}Received: ${color2}${totaldown wlan1}
    ${else}
    ${if_existing /proc/net/route eth1}
    ${voffset -305}${goto 40}${color5}Up: ${color2}${upspeed eth1}${color5}${goto 150}Down: ${color2}${downspeed eth1}
    ${voffset 10}${goto 40}${upspeedgraph eth1 26,80 d64937 d64937}${goto 150}${downspeedgraph eth1 26,80 d64937 d64937}
    ${voffset 9}${goto 40}${color5}Sent: ${color2}${totalup eth1}${color5}${goto 150}Received: ${color2}${totaldown eth1}
    ${else}
    ${if_existing /proc/net/route eth0}
    ${voffset -318}${goto 40}${color5}Up: ${color2}${upspeed eth0}${color5}${goto 150}Down: ${color2}${downspeed eth0}
    ${voffset 10}${goto 40}${upspeedgraph eth0 26,80 d64937 d64937}${goto 150}${downspeedgraph eth0 26,80 d64937 d64937}
    ${voffset 9}${goto 40}${color5}Sent: ${color2}${totalup eth0}${color5}${goto 150}Received: ${color2}${totaldown eth0}
    ${else}
    ${if_existing /proc/net/route enp0s0}
    ${voffset -331}${goto 40}${color5}Up: ${color2}${upspeed enp0s0}${color5}${goto 150}Down: ${color2}${downspeed enp0s0}
    ${voffset 10}${goto 40}${upspeedgraph enp0s0 26,80 d64937 d64937}${goto 150}${downspeedgraph enp0s0 26,80 d64937 d64937}
    ${voffset 9}${goto 40}${color5}Sent: ${color2}${totalup enp0s0}${color5}${goto 150}Received: ${color2}${totaldown enp0s0}
    ${else}
    ${if_existing /proc/net/route enp0s1}
    ${voffset -344}${goto 40}${color5}Up: ${color2}${upspeed enp0s1}${color5}${goto 150}Down: ${color2}${downspeed enp0s1}
    ${voffset 10}${goto 40}${upspeedgraph enp0s1 26,80 d64937 d64937}${goto 150}${downspeedgraph enp0s1 26,80 d64937 d64937}
    ${voffset 9}${goto 40}${color5}Sent: ${color2}${totalup enp0s1}${color5}${goto 150}Received: ${color2}${totaldown enp0s1}
    ${else}
    ${voffset -311}${goto 40}${color5}Network disconnected${color}
    ${image ~/.harmattan-assets/misc/Numix/God-Mode/offline.png -p 44,284 -s 16x16}
    ${endif}${endif}${endif}${endif}${endif}${endif}${endif}${endif}${endif}${endif}

    ${image ~/.harmattan-assets/misc/Numix/God-Mode/pressure.png -p 224,95 -s 16x16}
    ${image ~/.harmattan-assets/misc/Numix/God-Mode/humidity.png -p 224,115 -s 16x16}
    ${image ~/.harmattan-assets/misc/Numix/God-Mode/wind-2.png -p 224,136 -s 16x16}
    ${execi 300 cp -f ~/.harmattan-assets/icons/small---dcdcdc/$(grep "yweather:forecast" ~/.cache/weather.xml | grep -o "code=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*" | awk 'NR==1').png ~/.cache/weather-1.png}${image ~/.cache/weather-1.png -p 41,207 -s 32x32}
    ${execi 300 cp -f ~/.harmattan-assets/icons/small---dcdcdc/$(grep "yweather:forecast" ~/.cache/weather.xml | grep -o "code=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*" | awk 'NR==2').png ~/.cache/weather-2.png}${image ~/.cache/weather-2.png -p 119,207 -s 32x32}
    ${execi 300 cp -f ~/.harmattan-assets/icons/small---dcdcdc/$(grep "yweather:forecast" ~/.cache/weather.xml | grep -o "code=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*" | awk 'NR==3').png ~/.cache/weather-3.png}${image ~/.cache/weather-3.png -p 195,207 -s 32x32}${font}${voffset -120}\
]]
```

**Comment by zagortenay333** [comment] 2015-07-01 09:26
Oh wow. Conky 1.10 is a big update? :open_mouth:

From what I see at the terminal output, it seems to be able to use the old syntax, but it cannot read `undecorate`. Did you try to just write `undecorated` instead?

I will look into this whole 1.10 update. I'm still not getting it on fedora; still on 1.9.

**Comment by nicolasdanelon** [comment] 2015-07-01 14:33
I re-write that config and conky steel broken.. Now I don't have any  Invalid value or sintaxs errors.. don't worry, but please try to fix this, add this to you agenda =P 
and again, thanks for this awesome work!
Greetings from Argentina!

**Comment by zagortenay333** [comment] 2015-07-01 15:03
I won't fix this any time soon. The version 1.10 needs to be adopted wildly by different distros before I update it. You arch users are far too ahead of the rest of the gang :smile:

**Comment by nicolasdanelon** [comment] 2015-07-01 18:53
hahahahahahaha it's ok for me, because of that I said "don't worry" :P one more time... lovely bleeding edge software.. hahaha
what if you create a dev branch ? I can help you testing.

**Comment by zagortenay333** [comment] 2015-07-01 18:54
Frankly, too lazy. Conky is not the most exciting thing around for me.

**Comment by zoof** [comment] 2015-07-08 15:50
Same problem -- also an arch user.

**Comment by zoof** [comment] 2015-07-08 15:55
Downgraded to 1.9.0 and modified /etc/pacman.conf to "IgnorePkg = conky".  Working fine again.

**Comment by zagortenay333** [comment] 2015-07-08 16:07
The new syntax should have been made fully compatible with the old one though.

Now we have an awkward siituation where I can't update because most distros haven't updated to this version, and If I don't update arch users have to downgrade conky...

**Comment by nicolasdanelon** [comment] 2015-09-14 19:36
Hi :) what's the status of this issue

**Comment by zagortenay333** [comment] 2015-09-14 20:28
Didn't look into it either. I'm still getting conky `1.9.0` on latest fedora and ubuntu. Also, isn't this new syntax on the `lua-config` branch still; i.e., not yet merged to master? :confused: 
https://github.com/brndnmtthws/conky/tree/lua-config

**Comment by zagortenay333** [comment] 2015-09-14 20:29
Oh, just noticed they tagged the 1.10.0 release. Welp, I guess we're still gonna have to wait.

**Comment by nicolasdanelon** [comment] 2015-09-14 20:31
:'(

**Comment by zagortenay333** [comment] 2015-09-14 20:35
Tbh, I'm not looking forward to it. Updating Harmattan is not a gonna a walk in the park :grinning:. I don't think I'll be able to just batch edit all the damn .conkyrc files for this update..

**Comment by puneetmadaan164** [comment] 2015-10-29 17:58
If you guys are talking about the window around conky  do own_window_type to desktop or other possible values are normal, desktop, dock, panel or override. if you are feeling adventerous try override

if its flickering after this try setting double_buffer to yes

i am new to conky but still this thing worked for me

**Comment by zagortenay333** [comment] 2015-10-29 18:11
@puneetmadaan164 No, the issue is that conky version `1.10` uses a new syntax.

I could be wrong, but it seems that ubuntu 15.10's repository got the new conky.

**Comment by watho** [comment] 2015-11-06 10:20
Just want to let you know, that Ubuntu 15.10 uses conky 1.10.0.

**Comment by zagortenay333** [comment] 2015-11-06 23:12
On fedora 23 still `1.9.0`

**Comment by kachunkachunk** [comment] 2015-12-08 23:19
Man, getting Conky going from scratch is kind of irritating to say the least. This is probably one of the most drop-in friendly configs I've come across so far, but indeed Conky 1.10 seems to break stuff with its parsing assumptions.

Hoping you have some time to work on this soon, Zag. Understood if the prospect is terribly unexciting :P

**Comment by zagortenay333** [comment] 2015-12-08 23:42
@kachunkachunk Yeah I should start a new branch for `1.10`, but I'm too lazy right now... The official excuse is that fedora 23 still uses `1.9` though :stuck_out_tongue:

**Comment by nicolasdanelon** [comment] 2015-12-09 13:16
And this is how we look today.. this is your responsibility @kachunkachunk !! shame on you!
![screenshot from 2015-12-09 10-14-37](https://cloud.githubusercontent.com/assets/2846046/11686205/c1c749e0-9e5d-11e5-821d-90206f54aa78.png)

**Comment by SalahAdDin** [comment] 2016-02-06 08:27
You are a lazy guy man, i have the same problems, i'd working all afternoon trying to solve this problems and i couldn't it, i couldn't back off the fucking back ground, putting window_type in desktop i could back off the windowed view. I had to add the new wlan and eth0 protocols and finally i had to drop the background and i can't do it :'(
![conky tulipanrog _067](https://cloud.githubusercontent.com/assets/5034215/12865682/8f2542b0-cc81-11e5-8879-417df6426d8f.png)

**Comment by zagortenay333** [comment] 2016-02-06 15:52
@SalahAdDin I'm on fedora 23 still which uses `1.9.x`. When I upgrade to rawhide or 24, I'll start with this update.

Also, I'll need to finish a bigger update of the img assets and other things..

**Comment by SalahAdDin** [comment] 2016-02-06 17:30
Ah, ok, we waiting for you :D

**Comment by Cyberunner23** [comment] 2016-03-13 01:38
Any news?

**Comment by SalahAdDin** [comment] 2016-03-13 02:04
Now.

**Comment by zagortenay333** [comment] 2016-03-13 09:12
I'm still on version `1.9.x` :sweat_smile:

**Comment by ghost** [comment] 2016-03-25 16:28
Hey man no pressure. We'll be here... waiting... :baby:

**Comment by zagortenay333** [comment] 2016-04-04 21:52
Fixed as of 8690bbf08edd7d211e8a65e9ef8f1ca1c1bd6342.

If anyone has the `1.10.x` version of conky on ubuntu-based distros and doesn't have alignment issues, please confirm. I still get the same problem on openSUSE even on this newer version.

I'll open an issue against conky if that's the case.

**Closed as completed by zagortenay333** 2016-04-04 21:52 UTC

**Comment by nicolasdanelon** [comment] 2016-04-05 02:04
all this mouths without conky... 
thank you dudde!

**Comment by nicolasdanelon** [comment] 2016-04-05 02:35
life is too sad :(
![screenshot from 2016-04-04 23-33-31](https://cloud.githubusercontent.com/assets/2846046/14269750/d846b3f6-fabd-11e5-8d20-036c5456029e.png)

people how can I fix this ? please !

**Comment by nicolasdanelon** [comment] 2016-04-05 02:49
that is solve, I add Droid Sans but stills horrible 
![screenshot from 2016-04-04 23-48-26](https://cloud.githubusercontent.com/assets/2846046/14269943/c80b3848-fabf-11e5-9488-f53db0a0103b.png)

**Comment by zagortenay333** [comment] 2016-04-05 09:39
@nicolasdanelon This is the issue #1 . What distro are you on?

**Comment by greatquux** [comment] 2016-04-05 13:18
I had the same issue, on Ubuntu 15.10. However all alignment was fixed when I changed the "day names" on line 125 from "voffset 172" to "voffset 185" (which is the exact opposite of what the bug report says to do).

**Comment by zagortenay333** [comment] 2016-04-05 13:20
I'll open an issue against conky. Doubt anything will be done but whatever. It's freaking annoying.

**Comment by nicolasdanelon** [comment] 2016-04-05 20:58
I'm in ArchLinux

**Comment by zagortenay333** [comment] 2016-04-06 10:19
https://github.com/brndnmtthws/conky/issues/236

**Comment by JReque** [comment] 2016-04-09 14:03
I'm in ArchLinux and I have this problem too. Any solution?
Because of this problem I can not use Conky. :tired_face: 
Greeting waiting for a solution.

**Comment by zagortenay333** [comment] 2016-04-09 14:04
@Rekenium What do you mean? This issue is fixed.

**Comment by JReque** [comment] 2016-04-09 14:38
@zagortenay333 Network not found. Conky like this:
<a href="http://es.tinypic.com?ref=2u9papu" target="_blank"><img src="http://i65.tinypic.com/2u9papu.png" border="0" alt="Image and video hosting by TinyPic"></a>

Crash theme and no detected my network conection.
I use this config:
https://github.com/zagortenay333/Harmattan/blob/8690bbf08edd7d211e8a65e9ef8f1ca1c1bd6342/.harmattan-themes/Numix/God-Mode/normal-mode/.conkyrc

**Comment by zagortenay333** [comment] 2016-04-09 14:42
This issue is about supporting conky `1.10.x`.

The alignment issue has been already reported, and there is no solution. #1

**Comment by greatquux** [comment] 2016-04-09 14:49
You will have to modify the conkyrc file and replace for example ppp0 with the name of your active network connection.

**Comment by JReque** [comment] 2016-04-09 15:12
@greatquux @zagortenay333 Ok, thanks you very much guys.
@nicolasdanelon How you get alignment man? That theme do you use?

**Comment by zagortenay333** [comment] 2016-04-09 15:13
Stop commenting here please. This issue is closed.

**Comment by vaffluence** [comment] 2018-08-19 14:58
Unfortunately, I still have this issue in 18.04 Ubuntu.

"conky: '/home/vaff/.conkyrc' modified, reloading...
conky: Syntax error (/home/vaff/.conkyrc:2: unexpected symbol near '#') while reading config file. 
conky: Assuming it's in old syntax and attempting conversion.
conky: desktop window (800012) is subwindow of root window (122)
conky: window type - desktop
conky: drawing to created window (0x1c00002)
conky: drawing to double buffer"

**Comment by zagortenay333** [comment] 2018-08-19 15:07
@vaffluence what conkyrc are you using?

**Comment by vaffluence** [comment] 2018-08-19 16:05
Thanks for replying even though the thread is closed....

I am using conkywx v1.133 on Ubuntu 18.04 Lts.

**Comment by zagortenay333** [comment] 2018-08-19 16:08
I meant which conky file are you using; maybe there is a bug in it.

**Comment by vaffluence** [comment] 2018-08-19 16:25
Ok.The conkyrc file:

TEXT
${color #ffffff}
#${color #000000}

S Y S T E M    I N F O    L I N U X
${hr}
Host:$alignr$nodename
Kernel:$alignr$kernel
Uptime:$alignr$uptime
Disk usage:$alignr${fs_used /}/${fs_size /}
CPU usage:$alignr${cpu cpu0}%
${cpubar}
RAM:$alignr$mem/$memmax
Free Memory:$alignr${memeasyfree}
Swap usage:$alignr$swap/$swapmax
RAM${alignr}Disk I/O
     ${memgauge 30,80}          ${diskiograph 30,80}
${membar}

#${color white}Filesystem ${hr 1}${color}
F I L E S Y S T E M
${hr}
Root: ${alignr}${fs_free /} / ${fs_size /}
${fs_bar 4 /}
#dos: ${alignr}${fs_free /dos} / ${fs_size /dos}
#${fs_bar 4 /dos}

${color1}${font Alfios:size=12:bold}NETWORK${font}${color}${alignr}${wireless_essid wlp30}
${color5}Signal Quality${alignr}${color0}${wireless_link_bar 6,90 wlp3s0}

${color2}IP LOCAL: ${addr wlp3s0}
${color2}IP PUBLIC : ${color1}${texeci 3600 wget http://checkip.dyndns.org -O - -o /dev/null | cut -d : -f 2 | cut -d \< -f 1}

Down ${downspeed wlp3s0} k/s ${alignr}Up ${upspeed  wlp3s0} k/s
${downspeedgraph wlp3s0 35,107} ${alignr}${upspeedgraph wlp3s0 35,107}
Total ${totaldown wlp3s0} ${color}${alignr}${totaldown wlp3s0}${font}

#${color white}top${hr 1}${color}
T O P | M E M
${hr}
${top_mem name 1}${alignr 30}${top_mem cpu 1}${alignr}${top_mem pid 1}
${top_mem name 2}${alignr 30}${top_mem cpu 2}${alignr}${top_mem pid 2}
${top_mem name 3}${alignr 30}${top_mem cpu 3}${alignr}${top_mem pid 3}
${top_mem name 4}${alignr 30}${top_mem cpu 4}${alignr}${top_mem pid 4}
${top_mem name 5}${alignr 30}${top_mem cpu 5}${alignr}${top_mem pid 5}

**Comment by vaffluence** [comment] 2018-08-19 16:27
Here is the top script elements:

# conky configuration
# The list of variables has been removed from this file in favour
# of keeping the documentation more maintainable.
# Check http://conky.sf.net for an up-to-date-list.
#
# For ideas about how to modify conky, please see:
# http://crunchbanglinux.org/forums/topic/59/my-conky-config/
#
# For help with conky, please see:
# http://crunchbanglinux.org/forums/topic/2047/conky-help/
#
# Enjoy! :)
##############################################
# Settings
##############################################
#background yes
use_xft yes
xftfont Liberation Sans:size=9
xftalpha 1
update_interval 1.0
total_run_times 0
#own_window yes
#own_window_transparent yes 
##############################################
# Compositing tips:
# Conky can play strangely when used with
# different compositors. I have found the
# following to work well, but your mileage
# may vary. Comment/uncomment to suit.
##############################################
## no compositor
#own_window_type override
#own_window_argb_visual no
 
## xcompmgr
#own_window_type override
#own_window_argb_visual yes
 
## https://ubuntuforums.org/showthread.php?t=2070788
background yes
own_window yes
own_window_type desktop
own_window_transparent yes
own_window_argb_visual yes

##############################################
own_window_hints undecorated,below,sticky,skip_taskbar,skip_pager
double_buffer yes
minimum_size 200 200
maximum_width 200
draw_shades yes
draw_outline no
draw_borders no
draw_graph_borders no
default_color 656667
default_shade_color 000000
default_outline_color 828282
alignment top_right
gap_x 12
gap_y 15
no_buffers yes
uppercase no
cpu_avg_samples 2
override_utf8_locale no
##############################################
#  Output
##############################################

**Comment by zagortenay333** [comment] 2018-08-19 16:28
What is that? Are you sure you're using Harmattan?

**Comment by vaffluence** [comment] 2018-08-19 16:33
#background yes
use_xft yes
xftfont Liberation Sans:size=9
xftalpha 1
update_interval 1.0
total_run_times 0
#own_window yes
#own_window_transparent yes

## no compositor
#own_window_type override
#own_window_argb_visual no
 
## xcompmgr
#own_window_type override
#own_window_argb_visual yes
 
## https://ubuntuforums.org/showthread.php?t=2070788
background yes
own_window yes
own_window_type desktop
own_window_transparent yes
own_window_argb_visual yes


own_window_hints undecorated,below,sticky,skip_taskbar,skip_pager
double_buffer yes
minimum_size 200 200
maximum_width 200
draw_shades yes
draw_outline no
draw_borders no
draw_graph_borders no
default_color 656667
default_shade_color 000000
default_outline_color 828282
alignment top_right
gap_x 12
gap_y 15
no_buffers yes
uppercase no
cpu_avg_samples 2
override_utf8_locale no

#  Output

**Comment by zagortenay333** [comment] 2018-08-19 16:35
That's not a harmattan conkyrc..

**Comment by vaffluence** [comment] 2018-08-19 16:36
Sorry, it is not the Harmattan script that I am using.

**Comment by zagortenay333** [comment] 2018-08-19 16:39
From what I can tell the conkyrc file you're using is in the old syntax while you have conky 1.1x installed. The new syntax doesn't use the '#' char as comment.

**Comment by vaffluence** [comment] 2018-08-19 17:59
Thanks, I have replaced the whole conkyrc with the Harmattan script. Editing it now to see how it comes out.

**Comment by jaijujacob** [comment] 2020-04-03 09:35
Getting this error:
llua_load: cannot open ./rings-v1.3.1.lua: No such file or directory

Recently started getting this error message and Cairo rings are not getting displayed.

This is the line where the file is getting loaded.
# Lua Load  ##${voffset 750}
**lua_load ./rings-v1.3.1.lua**
#lua_draw_hook_pre ring_stats
lua_draw_hook_pre conky_main

Any help or suggestion?
