### ISSUE TITLE
Misaligned text

### ISSUE THREAD

**Issue by pallavahooja** [zagortenay333/Harmattan#14] opened 2016-04-02 08:43 UTC
After updating to the latest version my text is misaligned with the rest of the window/background. 

![selection_009](https://cloud.githubusercontent.com/assets/5708460/14225334/f00f16b4-f8dc-11e5-823d-ac94da07ff0f.png)

I am new to conky and was not able to debug much .

**Comment by zagortenay333** [comment] 2016-04-02 09:54
duplicate of #1

**Closed as completed by zagortenay333** 2016-04-02 09:54 UTC
