### ISSUE TITLE
Black background/shadow in Plasma 5

### ISSUE THREAD

**Issue by hrvoojex** [zagortenay333/Harmattan#40] opened 2017-05-21 00:45 UTC
Could you tell me what is the setup for not to have these black shadow arround a conky window?

![screenshot_20170521_024255](https://cloud.githubusercontent.com/assets/11456950/26280352/fd23f5d4-3dcf-11e7-9a9e-28df18f5dee6.png)

**Comment by zagortenay333** [comment] 2017-05-21 09:27
Duplicate of #3

**Closed as completed by zagortenay333** 2017-05-21 09:27 UTC
