### ISSUE TITLE
Black Border??

### ISSUE THREAD

**Issue by dhinakg** [zagortenay333/Harmattan#18] opened 2016-06-10 22:38 UTC
I have an ugly black border around the Harmattan conky. Every single theme.
![screenshot from 2016-06-10 18-38-08](https://cloud.githubusercontent.com/assets/17605561/15980544/7fdc4076-2f3a-11e6-9a57-baa9d8909ceb.png)

**Comment by zagortenay333** [comment] 2016-06-11 08:22
Duplicate of #3.

**Closed as completed by zagortenay333** 2016-06-11 08:22 UTC
