### ISSUE TITLE
" conky: unknown variable '$image' "

### ISSUE THREAD

**Issue by sarahsturgeon** [zagortenay333/Harmattan#26] opened 2016-09-26 14:36 UTC
Every time I start Conky with one of these themes, I always get spammed with the `unknown variable` error, and I don't see any images on my Conky. 

```
brandon@brandon-VirtualBox:~$ conky
conky: desktop window (2a0000a) is subwindow of root window (281)
conky: window type - normal
conky: drawing to created window (0x1a00001)
conky: drawing to double buffer
conky: Unknown setting 'imlib_cache_size'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: forked to background, pid is 8125
```

I'm running Ubuntu in Virtualbox. I have the latest version of Conky (`1.10.1` I believe.)
I'm using the `OMG-Ubuntu!` `God-Mode` theme, and I've replaced all of the `template` vars correctly.

Here's what my Conky looks like.

![conky](https://cloud.githubusercontent.com/assets/7936439/18838253/73310406-83cc-11e6-9096-525c3ca3bd5f.PNG)

Any ideas? All of the images should be touch-able. Running Conky with `sudo` doesn't make a difference.

**Comment by sarahsturgeon** [comment] 2016-09-26 14:43
[This](https://github.com/zagortenay333/Harmattan/issues/7#issuecomment-219260580) fixed it for me. I just installed `conky-all` 

But now I have some really weird visual bugs.
![conky2](https://cloud.githubusercontent.com/assets/7936439/18838580/97b8db2c-83cd-11e6-9d15-77aa56042c89.PNG)

Also the weather data has gone away (and it was previously working)

**Here's my `conky -v`**

```

brandon@brandon-VirtualBox:~$ conky -v
conky 1.10.1 compiled Wed Jan  6 17:11:44 UTC 2016 for Linux 3.19.0-43-generic x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib/conky


 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * Curl
  * RSS
  * Weather (METAR)
  * Weather (XOAP)
  * wireless
  * support for IBM/Lenovo notebooks
  * nvidia
  * eve-online
  * builtin default configuration
  * old configuration syntax
  * Imlib2
  * apcupsd
  * iostats
  * ncurses
  * Internationalization support

 Lua bindings:
  * Cairo
  * Imlib2
  * RSVG
 X11:
  * Xdamage extension
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * Audacious
  * MPD
  * MOC
  * XMMS2

 Default values:
  * Netdevice: eth0
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/share/locale
  * Maximum netdevices: 64
  * Maximum text size: 16384
  * Size text buffer: 256

```

**Comment by zagortenay333** [comment] 2016-09-26 14:55
Duplicate of #21

**Closed as completed by zagortenay333** 2016-09-26 14:55 UTC
